os: linux
sudo: false
dist: trusty
language: python
python:
  #- "2.7" # not supported
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  # run all tests even if errors appear
  - pytest --continue-on-collection-errors

# bypass submodules because gitlab requires authentication for pull
git:
  submodules: false
